### ISSUE TITLE
Not working with zendframework/zend-eventmanager (2.6.2)

### ISSUE THREAD

**Issue by manu777** [bjyoungblood/BjyAuthorize#303] opened 2016-02-12 10:03 UTC
The Module is not working correctly with the zendframework/zend-eventmanager (2.6.2)

It produce a Warning:
Warning: array_key_exists(): The first argument should be either a string or an integer ....

You can reproduce if you update your ZF2 Lib or the component "zend-eventmanager".

Can you fix this?

It works with zend-eventmanager (2.5.2)

**Comment by Ocramius** [comment] 2016-02-12 14:26
Duplicate of zendframework/zend-cache#71

**Closed by Ocramius** 2016-02-12 14:26 UTC
